"""BADNASS Dispatch Platform — Cryptographic Secret Generator.

Generates all secrets required by the application and writes them to:
  - .env       : actual runtime secrets (gitignored)
  - .env.example : redacted template for version control

Compliance:
  - CNDP Loi 09-08: PII_ENCRYPTION_KEY_BASE64 → AES-256-GCM (32-byte key)
  - GDPR Article 32: appropriate key lengths (256-bit AES, 256-bit HMAC)
"""

import base64
import secrets

# ── Generate all cryptographic secrets ─────────────────────────────────────
postgres_password = secrets.token_urlsafe(24)
redis_password = secrets.token_urlsafe(24)
jwt_secret_key = secrets.token_hex(32)
hmac_secret_key = secrets.token_hex(32)
pii_key_bytes = secrets.token_bytes(32)  # 256-bit key for AES-256-GCM
pii_encryption_key_base64 = base64.b64encode(pii_key_bytes).decode("ascii")
mock_client_secret = secrets.token_hex(16)  # For local dev/testing only

# ── Write .env (actual secrets — must be gitignored) ───────────────────────
env_lines = [
    "# BADNASS Dispatch Platform — Runtime Secrets",
    "# Generated by gen_env.py — DO NOT COMMIT THIS FILE",
    "",
    "# Application",
    "APP_ENV=production",
    "APP_PORT=8000",
    "",
    "# JWT Authentication (HS256)",
    f"SECRET_KEY={jwt_secret_key}",
    "JWT_ALGORITHM=HS256",
    "",
    "# HMAC Payload Integrity (SHA-256, constant-time verify)",
    f"HMAC_SECRET_KEY={hmac_secret_key}",
    "",
    "# PII Encryption — AES-256-GCM (CNDP Loi 09-08 / GDPR Art.32)",
    f"PII_ENCRYPTION_KEY_BASE64={pii_encryption_key_base64}",
    "",
    "# PostgreSQL (air-gapped DB)",
    "POSTGRES_USER=badnass_admin",
    f"POSTGRES_PASSWORD={postgres_password}",
    "POSTGRES_DB=badnass_dispatch",
    "POSTGRES_HOST=postgres",
    "POSTGRES_PORT=5432",
    "",
    "# Redis (JTI revocation + idempotency cache)",
    "REDIS_HOST=redis",
    "REDIS_PORT=6379",
    f"REDIS_PASSWORD={redis_password}",
    "",
    "# Dev/Test mock secret (local only)",
    f"MOCK_CLIENT_SECRET={mock_client_secret}",
]

with open(".env", "w") as f:
    f.write("\n".join(env_lines) + "\n")

# ── Write .env.example (redacted template — safe to commit) ─────────────────
example_lines = [
    "# BADNASS Dispatch Platform — Environment Variables Template",
    "# Copy to .env and fill in real values using gen_env.py",
    "",
    "# Application",
    "APP_ENV=production",
    "APP_PORT=8000",
    "",
    "# JWT Authentication (HS256)",
    "SECRET_KEY=<run: python gen_env.py>",
    "JWT_ALGORITHM=HS256",
    "",
    "# HMAC Payload Integrity",
    "HMAC_SECRET_KEY=<run: python gen_env.py>",
    "",
    "# PII Encryption — AES-256-GCM (CNDP Loi 09-08 / GDPR Art.32)",
    "PII_ENCRYPTION_KEY_BASE64=<run: python gen_env.py>",
    "",
    "# PostgreSQL",
    "POSTGRES_USER=badnass_admin",
    "POSTGRES_PASSWORD=<run: python gen_env.py>",
    "POSTGRES_DB=badnass_dispatch",
    "POSTGRES_HOST=postgres",
    "POSTGRES_PORT=5432",
    "",
    "# Redis",
    "REDIS_HOST=redis",
    "REDIS_PORT=6379",
    "REDIS_PASSWORD=<run: python gen_env.py>",
    "",
    "# Dev/Test mock secret",
    "MOCK_CLIENT_SECRET=<run: python gen_env.py>",
]

with open(".env.example", "w") as f:
    f.write("\n".join(example_lines) + "\n")

# ── Summary ──────────────────────────────────────────────────────────────────
print("=" * 60)
print("BADNASS Dispatch — Secrets Generated Successfully")
print("=" * 60)
print(f"  POSTGRES_PASSWORD      : {len(postgres_password)} chars  (token_urlsafe 24)")
print(f"  REDIS_PASSWORD         : {len(redis_password)} chars  (token_urlsafe 24)")
print(f"  JWT_SECRET_KEY         : {len(jwt_secret_key)} chars (token_hex 32 -> 256-bit)")
print(f"  HMAC_SECRET_KEY        : {len(hmac_secret_key)} chars (token_hex 32 -> 256-bit)")
pii_key_info = f"{len(pii_key_bytes) * 8}-bit AES key (base64: {len(pii_encryption_key_base64)} chars)"
print(f"  PII_ENCRYPTION_KEY     : {pii_key_info}")
print("=" * 60)
print("  .env         -> written (DO NOT COMMIT)")
print("  .env.example -> updated (safe to commit)")
print("=" * 60)
